### ISSUE TITLE
Change in file detected and application stops responding

### ISSUE THREAD

**Issue by kcd83** [xplicit/HyperFastCgi#25]
If a file is changed I get a message like
```
Change: Web.config
````
All future requests to the unix socket result in 504 gateway timeout (using nginx).

I suspect the application is supposed to reload however I couldn't find any relevant logic in hyperfastcgi. Where is the above message coming from?

**Comment by xplicit** [comment]
This message is coming from the System.Web, and than reloads the web application domain. HFC should handle this operation normally, do you use hyperfastcgi with managed config settings?

**Comment by kcd83** [comment]
Thanks for the response. I didn't realise this was `System.Web` doing that. 

We log a message in `Application_End` so we are seeing the shutdown but new requests do not trigger the application to start again, hence the 504s. Nothing in our log or hyperfastcgi's. I can also confirm hyperfastcgi no longer thinks the application is running because when we shut it down I no longer get the `System.NotImplementedException: The requested feature is not implemented.` error from `ManagedFastCgiListener.Shutdown()`.

Yes we are currently using `HyperFastCgi.Transports.ManagedFastCgiListenerTransport` and `HyperFastCgi.AppHosts.AspNet.AspNetApplicationHost`

**Comment by xplicit** [comment]
Looks like a mono bug. When mono unloads old domain and creates new one sometimes it messes the objects. For example, mono unloads domain with id=3 and creates next domain with id=1. But some objects in domain with id=1 are belonging to domain with id=4, which was never created. When HFC calls the object in this domain mono throws an exception.

Internal error: OutputPage threw an exception System.Runtime.Remoting.RemotingException: Server for uri 'd4eee666_9957_4575_850c_2b33c44cdf8e/1a84857e_3.rem' not found

I am going to isolate the bug and create and send small reproducible case to mono guys. While this issue won't be fixed in mono (or I won't find a workaround) I recommend reload HFC after changing web.config.

**Comment by xplicit** [comment]
Please try the latest commit  https://github.com/xplicit/HyperFastCgi/commit/53778f9a7c963ac88c50abe3328a543307ad1790

I am not sure it will help, but on my machine the exception has gone.

**Comment by kcd83** [comment]
Brilliant thanks

```
[2015-04-10 03:34:52Z] Debug   Configured host in domain 79e4cdae, id=1
Change: Web.config
[2015-04-10 03:38:53Z] Debug   Configured host in domain 79e4cdae, id=2
```
