### ISSUE TITLE
compile agains mono 4.8.0 fail

### ISSUE THREAD

**Issue by antonheryanto** [xplicit/HyperFastCgi#72]
using latest mono 4.8.0 branch to compile master branch failed because of this commit
https://github.com/mono/mono/commit/244124e6170ba0325f82e6545e5fd2b7cc62a788 as loader.h fail to load mono-dl.h

**Comment by xplicit** [comment]
It looks like mono bug, if this change breaks mono public API and loader.h includes file which is not public.

**Comment by xplicit** [comment]
I added bug to mono bugzilla https://bugzilla.xamarin.com/show_bug.cgi?id=47698

**Comment by antonheryanto** [comment]
thank very much

**Comment by xplicit** [comment]
It's fixed in mono master via https://github.com/mono/mono/commit/2df8d8091ef350c60fb801b17c44f65f7052e638 and should be backported to 4.8 branch. I close the issue, to monitor the state of backporting you can check this comment: 

 https://github.com/mono/mono/commit/244124e6170ba0325f82e6545e5fd2b7cc62a788#commitcomment-19936660
