### ISSUE TITLE
502 with Nginx

### ISSUE THREAD

**Issue by sgmesservey** [xplicit/HyperFastCgi#73]
Debian  7 Wheezy
Linux vm1 3.2.0-4-amd64 #1 SMP Debian 3.2.82-1 x86_64 GNU/Linux
(running from qemu w/ kvm & 1GB ram, 1 cpu)
Mono JIT compiler version 4.6.2 (Stable 4.6.2.7/08fd525 Mon Nov 14 12:30:00 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
nginx version: nginx/1.10.2 (also tried latest, 1.11.6)
HyperFastCgi.exe 0.4.4.0 (cloned today)
HFC started with:
 mono --debug /usr/local/src/HyperFastCgi/src/HyperFastCgi/4.0/bin/Release/HyperFastCgi.exe /config=/etc/nginx/hyper.config /stoppable=True /printlog=True /loglevels=All

I can't seem to get HyperFastCgi to respond to requests.

relevant nginx.conf:
 upstream fastcgi_backend {
      server unix:/var/tmp/hyper.sock;
      #server 127.0.0.1:9000;
      keepalive 32;
    }

    server {
        listen       80;
        server_name  vm1;
        charset utf-8;

        location / {
          root /opt/mytest;
          index index.html default.aspx Default.aspx;
        }

        location ~ \.(aspx|axd|ashx)$ {
          fastcgi_index Default.aspx;
          fastcgi_keep_conn on;
          fastcgi_pass fastcgi_backend;
          include /etc/nginx/fastcgi_params;
        }
}

hyper.config:

<configuration>
  <server type="HyperFastCgi.ApplicationServers.SimpleApplicationServer">
    <host-factory>HyperFastCgi.HostFactories.SystemWebHostFactory</host-factory>
    <threads min-worker="2" max-worker="5" min-io="4" max-io="0"/>
    <root-dir>/opt/mytest</root-dir>
  </server>
  <listener type="HyperFastCgi.Listeners.NativeListener">
    <apphost-transport type="HyperFastCgi.Transports.NativeTransport">
      <multithreading>ThreadPool</multithreading>
    </apphost-transport>
    
    <protocol>Unix</protocol>
    <address>/var/tmp/hyper.sock</address>
  </listener>
  <apphost type="HyperFastCgi.AppHosts.AspNet.AspNetApplicationHost">
    <log level="All" write-to-console="true"/>
    <add-trailing-slash>false</add-trailing-slash>
  </apphost>
  <web-applications>
    <web-application>
      <name>Default</name>
      <vhost>vm1</vhost>
      <vport>80</vport>
      <vpath>/</vpath>
      <path>/opt/mytest</path>
    </web-application>
  </web-applications>
</configuration>

I tried switching protocols to tcp, same thing.
I captured the nginx debug log, and the output of the console running HFC,
you can see them here:
https://gist.github.com/sgmesservey/7482974314f55956d25f18e5247f8597

You can see when nginx connects, then there is some weird recv() error (resource unavailabe), then nginx times out and closes the connection, which HFC notices.

Thank you for your time

**Comment by xplicit** [comment]
Can you show your hyper.config? 

What I see from the logs that you must increase max number of workers thread. Max of 5 worker threads is too low and might be the cause of the issue. Also you might want to decrease max number of IO threads (but it's not necessary).

**Comment by sgmesservey** [comment]
Sorry, it didn't paste. Here it is:
```xml
<!-- vim: set ft=xml: -->
<configuration>
  <server type="HyperFastCgi.ApplicationServers.SimpleApplicationServer">
    <host-factory>HyperFastCgi.HostFactories.SystemWebHostFactory</host-factory>
    <threads min-worker="2" max-worker="5" min-io="4" max-io="0"/>
    <root-dir>/opt/mytest</root-dir>
  </server>
  <listener type="HyperFastCgi.Listeners.NativeListener">
    <apphost-transport type="HyperFastCgi.Transports.NativeTransport">
      <multithreading>ThreadPool</multithreading>
    </apphost-transport>
    <!--
    <protocol>InterNetwork</protocol>
    <address>127.0.0.1</address>
    <port>9000</port>
    -->
    <protocol>Unix</protocol>
    <address>/var/tmp/hyper.sock</address>
  </listener>
  <apphost type="HyperFastCgi.AppHosts.AspNet.AspNetApplicationHost">
    <log level="All" write-to-console="true"/>
    <add-trailing-slash>false</add-trailing-slash>
  </apphost>
  <web-applications>
    <web-application>
      <name>Default</name>
      <vhost>vm1</vhost>
      <vport>80</vport>
      <vpath>/</vpath>
      <path>/opt/mytest</path>
    </web-application>
  </web-applications>
</configuration>
```

**Comment by sgmesservey** [comment]
Increasing the worker to threads to min:5 and max:20 seems to have done the trick,
the test aspx page and ashx handler work now.
My target platform is a VPS with 1GB, and I need somewhat less than half of that for a database,
so I am keen to keep memory usage down.

**Comment by xplicit** [comment]
20 threads is still very low, because you use ThreadPool settings in multithreading and every request running in parallel uses at least one thread (if you use network connections to database it produces much more). Moreover ASP.NET can spawn additional threads when cancel request, etc. In this case if you get several parallel requests simultaneously they will be queued into queue and executed one by one in best case in worst case they can deadlock each other (depends on the logic you have in the code). For example there was an issuee, when limiting max number of threadpool threads in monodevelop did not allow to use nuget to run simultaneous download of the packages, it simply hung when trying to use `HttpWebRequest` because it cannot spawn threads more then the limited number. 

512 MB is a quite large amount of memory and you should not limit maximal number of threads to such low numbers otherwise you will get unpredictable behaviour when running code depending on threadpool. Moreover I would recommend to increase min threads number, because every time when ASP.NET handles request it must create new thread (because there is no free threads on threadpool) which is resources-consuming operation. After handling requests thread is destroyed.

If you want to limit number of parallel requests to only one at a time, you should change Multithreading option from `ThreadPool` to `Single`

**Comment by sgmesservey** [comment]
Will adjust, thank you.
